frase = str(input("Entre com seu nome completo: ")).strip()
maiúsculo = frase.upper()
print(maiúsculo)
minúsculo = frase.lower()
print(minúsculo)
junção = frase.split()
soma = ('').join(junção)
print(soma)
print(len(soma))
print(len(junção [0]))